<a href="https://colab.research.google.com/github/Lucasvieirar/Pandas-Masterclass/blob/main/Aula_2_Domine_a_Importacao_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Aula 02

In [ ]:
import numpy as np
import pandas as pd

## Preparando o laboratório

In [ ]:
dados = {
    'ID venda': range(1, 101),
    'Produto': np.random.choice(['Notebook', 'Tablet', 'Celular'], 100),
    'Preço': np.random.uniform(1000, 5000, 100).round(2),
    'Data': pd.date_range(start='2025-01-01', periods=100)
}

# Criar o DataFrame
df = pd.DataFrame(dados)

# Salvar o DataFrame
df.to_csv('vendas.csv', index=False, sep=';')
df.to_excel('vendas.xlsx', index=False, sheet_name='Vendas')
df.to_parquet('vendas.parquet', index=False)
print('Arquios criados com sucesso!')

Arquios criados com sucesso!

##  CSV: Lidando com o caos

In [ ]:
df_csv = pd.read_csv(
    '/content/vendas.csv',
    sep=';',  # define o separador correto
    encoding='utf-8',  # tipo mais comum de codificação
    usecols=['Produto', 'Preço'],  # seleciona somente as colunas que importam para a análise
    nrows=10  # carrega apenas as 10 primeiras linhas do conjunto
)
df_csv

    Produto    Preço
0   Celular  3466.31
1  Notebook  3100.69
2    Tablet  3522.07
3  Notebook  3177.20
4    Tablet  2018.05
5  Notebook  2041.86
6  Notebook  2479.43
7    Tablet  4760.37
8    Tablet  1325.13
9   Celular  3995.08

## Excel: o formato corporativo

In [ ]:
# Carregar o arquivo Excel
df_excel = pd.read_excel(
    '/content/vendas.xlsx',
    sheet_name='Vendas'
)
df_excel

    ID venda   Produto    Preço       Data
0          1   Celular  3466.31 2025-01-01
1          2  Notebook  3100.69 2025-01-02
2          3    Tablet  3522.07 2025-01-03
3          4  Notebook  3177.20 2025-01-04
4          5    Tablet  2018.05 2025-01-05
..       ...       ...      ...        ...
95        96  Notebook  2679.44 2025-04-06
96        97    Tablet  3824.50 2025-04-07
97        98  Notebook  1097.73 2025-04-08
98        99   Celular  3286.25 2025-04-09
99       100   Celular  3975.85 2025-04-10

[100 rows x 4 columns]

## Parquet: a escolha dos profissionais

In [ ]:
df_parquet = pd.read_parquet('/content/vendas.parquet')
df_parquet

    ID venda   Produto    Preço       Data
0          1   Celular  3466.31 2025-01-01
1          2  Notebook  3100.69 2025-01-02
2          3    Tablet  3522.07 2025-01-03
3          4  Notebook  3177.20 2025-01-04
4          5    Tablet  2018.05 2025-01-05
..       ...       ...      ...        ...
95        96  Notebook  2679.44 2025-04-06
96        97    Tablet  3824.50 2025-04-07
97        98  Notebook  1097.73 2025-04-08
98        99   Celular  3286.25 2025-04-09
99       100   Celular  3975.85 2025-04-10

[100 rows x 4 columns]

In [ ]:
# Comparação entre o CSV e Parquet
df_csv = pd.read_csv('/content/vendas.csv', sep=';')

print(f'''dtype de "Data" no CSV: {df_csv["Data"].dtype}
dtype do "Data" no Parquet: {df_parquet["Data"].dtype}''')

dtype de "Data" no CSV: object
dtype do "Data" no Parquet: datetime64[ns]