<a href="https://colab.research.google.com/github/Lucasvieirar/Pandas-Masterclass/blob/main/Aula_1_Criando_seu_Primeiro_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 01

## Mão na massa: Criando o seu primeiro Dataset

In [ ]:
#importar o Pandas
import pandas as pd

In [ ]:
# Criar uma Series
precos = pd.Series(data=[4500, 1200, 300, 8000], name="Preços")
precos

0    4500
1    1200
2     300
3    8000
Name: Preços, dtype: int64

In [ ]:
# Criar um DataFrame
dados_loja = {
    'Produto': ['MacBook Pro', 'Teclado mecânico', 'Mouse Gamer', 'Monitor 4k'],
    'Categoria': ['Computadores', 'Acessórios', 'Acessórios', 'Monitores'],
    'Preço': [15000, 450, 300, 3500],
    'Estoque': [5, 15, 20, 10],
    'Data entrada': ['2023-01-10', '2023-02-15', '2023-02-20', '2023-03-01']
}

df = pd.DataFrame(dados_loja)
df

            Produto     Categoria  Preço  Estoque Data entrada
0       MacBook Pro  Computadores  15000        5   2023-01-10
1  Teclado mecânico    Acessórios    450       15   2023-02-15
2       Mouse Gamer    Acessórios    300       20   2023-02-20
3        Monitor 4k     Monitores   3500       10   2023-03-01

## Anatomia de um DataFrame

In [ ]:
# Verificar os compomentes da tabela
print(f'''Colunas: {df.columns}
      índixes: {df.index}
      Formato (linhas, colunas): {df.shape}
      Tipo de dados em cada Coluna: \n{df.dtypes}''')

Colunas: Index(['Produto', 'Categoria', 'Preço', 'Estoque', 'Data entrada'], dtype='object')
      índixes: RangeIndex(start=0, stop=4, step=1)
      Formato (linhas, colunas): (4, 5)
      Tipo de dados em cada Coluna:
Produto         object
Categoria       object
Preço            int64
Estoque          int64
Data entrada    object
dtype: object

## Índices de um Dataframe

In [ ]:
dados_loja = {
    'Produto': ['MacBook Pro', 'Teclado mecânico', 'Mouse Gamer', 'Monitor 4k'],
    'Categoria': ['Computadores', 'Acessórios', 'Acessórios', 'Monitores'],
    'Preço': [15000, 450, 300, 3500],
    'Estoque': [5, 15, 20, 10],
    'Data entrada': ['2023-01-10', '2023-02-15', '2023-02-20', '2023-03-01']
}

df = pd.DataFrame(dados_loja, index=['ID 430', 'ID 931', 'ID 187', 'ID  277'])
df

                  Produto     Categoria  Preço  Estoque Data entrada
ID 430        MacBook Pro  Computadores  15000        5   2023-01-10
ID 931   Teclado mecânico    Acessórios    450       15   2023-02-15
ID 187        Mouse Gamer    Acessórios    300       20   2023-02-20
ID  277        Monitor 4k     Monitores   3500       10   2023-03-01

In [ ]:
#Transformar uma coluna no índice
dados_loja = {
    'Produto': ['MacBook Pro', 'Teclado mecânico', 'Mouse Gamer', 'Monitor 4k'],
    'Categoria': ['Computadores', 'Acessórios', 'Acessórios', 'Monitores'],
    'Preço': [15000, 450, 300, 3500],
    'Estoque': [5, 15, 20, 10],
    'Data entrada': ['2023-01-10', '2023-02-15', '2023-02-20', '2023-03-01']
}

df = pd.DataFrame(dados_loja)
df = df.set_index('Produto')
df

                     Categoria  Preço  Estoque Data entrada
Produto
MacBook Pro       Computadores  15000        5   2023-01-10
Teclado mecânico    Acessórios    450       15   2023-02-15
Mouse Gamer         Acessórios    300       20   2023-02-20
Monitor 4k           Monitores   3500       10   2023-03-01

## Um DataFrame nada mais é do que o coletivo de Series

In [ ]:
dados_loja = {
    'Produto': pd.Series(['MacBook Pro', 'Teclado mecânico', 'Mouse Gamer', 'Monitor 4k'],
                         index=['ID 430', 'ID 931', 'ID 187', 'ID 277']),
    'Categoria': pd.Series(['Computadores', 'Acessórios', 'Acessórios', 'Monitores'],
                           index=['ID 430', 'ID 931', 'ID 187', 'ID 277']),
    'Preço': pd.Series([15000, 450, 300, 3500],
                       index=['ID 430', 'ID 931', 'ID 187', 'ID 277']),
    'Estoque': pd.Series([5, 15, 20, 10],
                         index=['ID 430', 'ID 931', 'ID 187', 'ID 277']),
    'Data entrada': pd.Series(['2023-01-10', '2023-02-15', '2023-02-20', '2023-03-01'],
                              index=['ID 430', 'ID 931', 'ID 187', 'ID 277'])
}

df = pd.DataFrame(dados_loja)

df

                 Produto     Categoria  Preço  Estoque Data entrada
ID 430       MacBook Pro  Computadores  15000        5   2023-01-10
ID 931  Teclado mecânico    Acessórios    450       15   2023-02-15
ID 187       Mouse Gamer    Acessórios    300       20   2023-02-20
ID 277        Monitor 4k     Monitores   3500       10   2023-03-01

In [ ]:
# Acesar uma coluna
df['Estoque']

ID 430     5
ID 931    15
ID 187    20
ID 277    10
Name: Estoque, dtype: int64

In [ ]:
# Acessar duas ou mais tabelas
df[['Data entrada', 'Produto', 'Preço']]

       Data entrada           Produto  Preço
ID 430   2023-01-10       MacBook Pro  15000
ID 931   2023-02-15  Teclado mecânico    450
ID 187   2023-02-20       Mouse Gamer    300
ID 277   2023-03-01        Monitor 4k   3500